# -*- coding: utf-8 -*-
from skimage.feature import canny, corner_harris, corner_peaks
import numpy as np
import matplotlib.pyplot as plt
from skimage.io import imread

# 1.1
hand = imread('hand.tiff', as_gray=True)
hand_1 = canny(hand, sigma=1)
hand_2 = canny(hand, sigma=1, low_threshold=100, high_threshold=None)
hand_3 = canny(hand, sigma=1, low_threshold=50, high_threshold=100)
hand_4 = canny(hand, sigma=2)
hand_5 = canny(hand, sigma=2, low_threshold=100, high_threshold=None)
hand_6 = canny(hand, sigma=2, low_threshold=50, high_threshold=100)

fig, axs = plt.subplots(2, 4, figsize=(20,10))
axs[0,0].imshow(hand, cmap='gray')
axs[0,0].set_title('Original image')
axs[0,0].axis('off')
axs[0,1].imshow(hand_1, cmap='gray')
axs[0,1].set_title('sigma=1.0, low=None, high=None')
axs[0,1].axis('off')
axs[0,2].imshow(hand_2, cmap='gray')
axs[0,2].set_title('sigma=1.0, low=100, high=None')
axs[0,2].axis('off')
axs[0,3].imshow(hand_3, cmap='gray')
axs[0,3].set_title('sigma=1.0, low=50, high=100')
axs[0,3].axis('off')
axs[1,0].imshow(hand, cmap='gray')
axs[1,0].set_title('Original image')
axs[1,0].axis('off')
axs[1,1].imshow(hand_4, cmap='gray')
axs[1,1].set_title('sigma=2.0, low=None, high=None')
axs[1,1].axis('off')
axs[1,2].imshow(hand_5, cmap='gray')
axs[1,2].set_title('sigma=2.0, low=100, high=None')
axs[1,2].axis('off')
axs[1,3].imshow(hand_6, cmap='gray')
axs[1,3].set_title('sigma=2.0, low=50, high=100')
axs[1,3].axis('off')
plt.show()

# 1.2
modelhouses = imread('modelhouses.png', as_gray=True)
modelhouses_1 = corner_harris(modelhouses, k=0.10, sigma=1)
modelhouses_2 = corner_harris(modelhouses, k=0.20, sigma=1)
modelhouses_3 = corner_harris(modelhouses, k=0.10, sigma=2)
modelhouses_4 = corner_harris(modelhouses, k=0.20, sigma=2)

fig, axs = plt.subplots(2, 3, figsize=(15,8))
axs[0,0].imshow(modelhouses, cmap='gray')
axs[0,0].set_title('Original image')
axs[0,0].axis('off')
axs[0,1].imshow(modelhouses_1, cmap='gray')
axs[0,1].set_title('k=0.10, sigma=1')
axs[0,1].axis('off')
axs[0,2].imshow(modelhouses_2, cmap='gray')
axs[0,2].set_title('k=0.20, sigma=1')
axs[0,2].axis('off')
axs[1,0].imshow(modelhouses, cmap='gray')
axs[1,0].set_title('Original image')
axs[1,0].axis('off')
axs[1,1].imshow(modelhouses_3, cmap='gray')
axs[1,1].set_title('k=0.10, sigma=2')
axs[1,1].axis('off')
axs[1,2].imshow(modelhouses_4, cmap='gray')
axs[1,2].set_title('k=0.20, sigma=2')
axs[1,2].axis('off')
plt.tight_layout()
plt.show()

modelhouses_1 = corner_harris(modelhouses, method='eps', eps=1e-30, sigma=2)
modelhouses_2 = corner_harris(modelhouses, method='eps', eps=1e-20, sigma=2)
modelhouses_3 = corner_harris(modelhouses, method='eps', eps=1e-10, sigma=2)
modelhouses_4 = corner_harris(modelhouses, method='eps', eps=1e-05, sigma=2)
modelhouses_5 = corner_harris(modelhouses, method='eps', eps=1e-01, sigma=2)


fig, axs = plt.subplots(2, 3, figsize=(14,8))
axs[0,0].imshow(modelhouses, cmap='gray')
axs[0,0].set_title('Original image')
axs[0,0].axis('off')
axs[0,1].imshow(modelhouses_1, cmap='gray')
axs[0,1].set_title('eps=1e-30, sigma=2')
axs[0,1].axis('off')
axs[0,2].imshow(modelhouses_2, cmap='gray')
axs[0,2].set_title('eps=1e-20, sigma=2')
axs[0,2].axis('off')
axs[1,0].imshow(modelhouses_3, cmap='gray')
axs[1,0].set_title('eps=1e-10, sigma=2')
axs[1,0].axis('off')
axs[1,1].imshow(modelhouses_4, cmap='gray')
axs[1,1].set_title('eps=1e-05, sigma=2')
axs[1,1].axis('off')
axs[1,2].imshow(modelhouses_5, cmap='gray')
axs[1,2].set_title('eps=1e-01, sigma=2')
axs[1,2].axis('off')
plt.tight_layout()
plt.show()

# 1.3
modelhouses = imread('modelhouses.png', as_gray=True)
corner = np.array(corner_peaks(corner_harris(modelhouses, k=0.30, sigma=5)))
plt.imshow(modelhouses, cmap='gray')
plt.scatter(corner[:,1], corner[:,0], marker='.', c='red')
plt.show()